# Uncomment the next line to define a global platform for your project
platform :ios, '17.0'
source 'https://cdn.cocoapods.org/'
source 'https://github.com/shapeddev/shaped-sdk-ios-specs.git'

target 'ShapedExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  use_modular_headers!

  # Pods for Shaped
  pod 'shaped_plugin_camera', '0.0.1'
  pod 'shaped_sdk', '0.0.1'

end
