platform :ios, '13.0'
source 'https://cdn.cocoapods.org/'
source 'https://github.com/shapeddev/shaped-sdk-ios-specs.git'

target 'Shaped' do
  use_frameworks!
  use_modular_headers!

  pod 'shaped_sdk', '0.0.1'
end
